name: decidim CD

on:
  workflow_call:
  workflowdispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    uses: yukioz/GCES_TF_CI/.github/workflows/ci.yml@main
  deploy:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
