name: Ruby on Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@postgres/test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis-queue:
        image: redis:6.0.12-alpine
      redis-cache:
        image: redis:6.0.12-alpine

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker-compose build

      - name: Set up the database
        run: docker-compose run --rm app bundle exec rails db:create db:schema:load

      - name: Run tests
        run: docker-compose run --rm app bundle exec rails test

      - name: Run RuboCop
        continue-on-error: true
        run: docker-compose run --rm app bundle exec rubocop
