name: Ruby on Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:${{ secrets.DATABASE_PASSWORD }}@postgres/test
  ALLOW_HOSTS: ${{ secrets.ALLOW_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v2
      -name: Build do app
        run: docker-compose up --build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      -uses: actions/checkout@v2
      -name: unit tests
        run: docker-compose run --rm app bundle exec rails test


  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
      -uses: actions/checkout@v2
      -name: rubocop
        run: docker-compose run --rm app bundle exec rubocop
