name: CI from decidim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: test

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build
        run: docker-compose build

      - name: Run tests
        run: docker-compose run --rm app bundle exec rails test

      - name: Run RuboCop lint
        continue-on-error: true
        run: docker-compose run --rm app bundle exec rubocop
